Lesson 7
foxy-eyed/helloReact pull request #10
Opened 2018-08-27 11:04 UTC by foxy-eyed

- [x] Реализуйте сохранение состояния корзины в localStorage 
- [ ] Реализуйте API Middleware наподобие тому, что было разобрано в уроке. Сделайте все action-creator'ы в вашем приложении декларативными.
- [ ] Реализуйте форму отправки заказа (сам заказ, контактные данные клиента: ФИО, телефон, email, адрес). Валидируйте корректность заполнения полей. При отправке заказа следует очищать корзину и отправлять JSON-документ заказа по некоторому адресу.

2018-09-03 21:19 UTC, indevelope requested changes
Нужно отделить презентационную логику от контейнерных компонентов, нужно избавиться от побочного эффекта в reducer'e

2018-09-03 21:19 UTC, indevelope commented on src/actions/catalog.js
> +      access_token: contentful.token,
авторизацию лучше всего подмешивать в middleware, заодно не будет мешанины связанной с камелизацией/декамелизацией ключей

2018-09-03 21:19 UTC, indevelope commented on src/components/views/Order/index.js
> +import OrderContainer from '~/src/containers/Order/';
практика показывает, что контейнер бывает полезно держать поближе к компоненту, то есть нето типа

```
./Order
./Order.js – тут презентационный компонент
./index.js – тут контейнер
```

P.S: это просто заметка, можешь оставить на свой вкус и цвет

2018-09-03 21:19 UTC, indevelope commented on src/containers/Order/OrderForm.js
> +export default reduxForm({
checkRequired, validate и reduxForm можно было бы выделить в отдельный модуль-контейнер.  Когда форма станет сложнее, будет проще отделить контейнерную логику от презентационной

2018-09-03 21:19 UTC, indevelope commented on src/containers/Order/index.js
> +      <Fragment>
презентация попала в контейнер

2018-09-03 21:19 UTC, indevelope commented on src/reducers/order.js
> +      console.log(action.error);
console.log это побочный эффект, не должно быть в чистом reducer'e. Обычная практика - загнать информацию об ошибке в состояние и отобразить из презентационного компонента

2018-09-04 11:56 UTC, foxy-eyed commented on src/actions/catalog.js
> +      access_token: contentful.token,
Сейчас middleware у нас вроде как универсальный получается для разных api, способы аутентификации у них могут быть разные. В данном случае через query-params токен передается, для гугл-таблиц, куда я отсылаю заказ, она вообще не нужна.
Поэтому в текущей ситуации кажется логичным передавать эти параметры извне.
Если бы я делала свой middleware под каждый сервис, утащила бы эти детали внутрь.

2018-09-05 01:17 UTC, index01d commented on src/actions/catalog.js
> +      access_token: contentful.token,
Или можно сделать общий middleware и конкретную спецификацию под каждый сервис. В любом случае наделять actionCreator знанием о тонкостях авторизации опасно с тз дальнейшего развития приложения, нужно удержать эту логику в рамках middleware

2018-09-05 01:24 UTC, index01d requested changes
только сейчас словил несколько моментов
1) handleSubmit оказался в OrderContainer, уместнее было бы утащить его в OrderFormContainer, в качестве параметра onSubmit для опций reduxForm. метод 
2) Форма и так получит от redux-form в качестве свойства метод reset() (передача resetForm выглядит избыточной) https://redux-form.com/7.4.2/docs/api/reduxform.md/#-code-reset-void-code-
таким образом выглядит так, что весь контейнер можно соединить с OrderFormContainer, недостающие поля доцеплять там же reduxForm(...)(connect(...)(Component))

2018-09-14 14:09 UTC, foxy-eyed commented on src/actions/catalog.js
> +      access_token: contentful.token,
@index01d посмотри, плиз, так пойдёт?
https://github.com/foxy-eyed/helloReact/pull/10/commits/d3b8acf6a10f0781d4013f87ac2a69144239ff00

2018-09-14 14:13 UTC, foxy-eyed commented
@index01d я перетащила логику сабмита в ф-ю в контейнер формы: https://github.com/foxy-eyed/helloReact/pull/10/commits/a494e790dd172e9df409ef660594cf5f6132e8ed
Я так поняла, ты хотел, чтобы в итогу вообще только контейнер формы один остался?
Но я все-таки `OrderContainer` оставила, он стал совсем простой, чтобы просто пропсы из стора передавать в презентационный компонент. В контейнере формы, мне показалось, этому не место.

2018-09-16 07:45 UTC, index01d approved these changes

2018-09-18 09:32 UTC, merged