Lesson3
foxy-eyed/helloReact pull request #4
Opened 2018-07-25 16:28 UTC by foxy-eyed

- [x] Добавьте на страницу с каталогом кнопку корзины со счетчиком добавленных покупок
- [x] Добавьте на карточку продукта кнопку добавления в корзину
- [x] Создайте модуль с контекстом-содержимым корзины
- [x] Создайте в контейнерном компоненте поле состояния для хранения списка покупок
- [x] Используя Provider и Consumer передайте компоненту кнопки корзины данные о содержимом корзины в состоянии
- [x] Аналогично реализуйте добавление в корзину с помощью кнопки на карточке продукта

![pvnakcrxsg](https://user-images.githubusercontent.com/19491749/43356823-07ad644a-9289-11e8-9702-630750354138.gif)

2018-07-29 08:17 UTC, index01d requested changes

2018-07-29 08:17 UTC, index01d commented on src/components/Cart.js
> +          <div className="card-header">
неплохо было бы выделять презентационные компоненты - части карточки `<CardHeader />`, `<CardBody />`

2018-07-29 08:17 UTC, index01d commented on src/components/Cart.js
> +              items.map(itemData => (
лучше не создавать новых имен (чем их меньше, тем лучше). Название аргумента product было бы куда понятнее

2018-07-29 08:17 UTC, index01d commented on src/constants/propTypes.js
> +import PropTypes from 'prop-types';
не стоит декомпозировать все propType в модуль, лучше определять их в модуле с компонентом-потребителем.

2018-07-29 08:17 UTC, index01d commented on src/containers/App.js
> +      <div className="container-fluid">
стоило бы выделить презентационный компонент `<Container fluid>` и вообще обратить внимание на reactstrap (https://reactstrap.github.io/)

2018-07-29 08:17 UTC, index01d commented on src/containers/App.js
> +        <div className="row">
аналогично `<Row />`

2018-07-29 08:17 UTC, index01d commented on src/components/Catalog.js
> +    <CartContextConsumer>
здесь явно не требуется использовать Consumer. Его нужно использовать в компоненте кнопки добавления товара в корзину, который нужно выделить из карточки, тогда код компонентов каталога и карточки товара останется чистым

2018-07-29 08:17 UTC, index01d commented on src/components/ProductCard.js
> +        <button
заслуживает выделения в отдельный компонент

2018-07-29 08:17 UTC, index01d commented on src/containers/CartProvider.js
> +    const itemPosition = this.addedProductsIds().indexOf(product.id);
код будет проще и не потребует вспомогательного метода addedProductsIds (с неговорящим названием, кстати), если сделать метод findOrCreateItem, используя findIndex из библиотеки lodash.

2018-07-29 08:17 UTC, index01d commented on src/containers/CartProvider.js
> +    this.setState({ items: updatedItems, count: count + quantity, sum: sum + product.price * quantity });
count и sum (принято называть обычно total) можно было бы сделать методами провайдера. Тогда в состоянии не было бы полей, которые можно посчитать из состояния и мы бы продолжали следовать правилам максимально чистого состояния.

2018-07-29 20:26 UTC, foxy-eyed commented on src/containers/App.js
> +      <div className="container-fluid">
Я думала, это будет читерство)) Но раз ты сам посоветовал, прикрутила!

2018-07-29 20:36 UTC, foxy-eyed commented on src/constants/propTypes.js
> +import PropTypes from 'prop-types';
@index01d 
Может быть, у меня 'dry головного мозга', но я это осмысленно сделала, чтобы переиспользовать шейпы, у которых несколько компонентов-потребителей.
Например, для описания объекта продукта – `productPropType`
[раз](https://github.com/foxy-eyed/helloReact/pull/4/files#diff-739e78bc33ca10f24a9038a076a9c642R18)
```
Catalog.propTypes = {
  products: PropTypes.arrayOf(productPropType).isRequired,
};
```
[два](https://github.com/foxy-eyed/helloReact/pull/4/files#diff-cb3fadfe06fe61f339b6a18f21631bf3R22)
```
ProductAddButton.propTypes = {
  product: productPropType.isRequired,
};
```
[три](https://github.com/foxy-eyed/helloReact/pull/4/files#diff-d008b546c2af5cbbc1fb623d9931bc33R28)
```
ProductCard.propTypes = {
  product: productPropType.isRequired,
};
```
Сейчас, если у меня у продукта изменятся поля или их тип, мне достаточно будет поменять их в одном месте.
Я бы оставила)

2018-07-30 12:06 UTC, index01d commented on src/constants/propTypes.js
> +import PropTypes from 'prop-types';
можно было бы просто PropTypes.arrayOf(ProductCard.propTypes.product) как вариант, тогда всегда будет ясен конечный потребитель

2018-07-30 12:14 UTC, index01d approved these changes
для опредленности можно было бы еще выделить контейнер с продуктами из CatalogPage.js (часть где продукты заезжают в состояние и передаются ниже по иерархии), например тоже с помощью контекста

2018-07-30 12:14 UTC, index01d commented on src/components/ProductAddButton.js
> +function ProductAddButton({ product }) {
лучше бы конечно AddToCartButton для определенности

2018-07-30 12:14 UTC, index01d commented on src/containers/CartProvider.js
>      const updatedItems = [...items];
`const items = [...this.state.items, addedItem];`
`this.setState({ item })` 
смотрелось бы чутка опрятнее

2018-07-30 12:30 UTC, foxy-eyed commented on src/containers/CartProvider.js
>      const updatedItems = [...items];
@index01d 
В плане кода – да, но я же обрабатываю еще ситуацию, когда данная позиция уже есть в корзине, и мне надо оставить ее на том же месте, просто добавив единиц товара и заинкрементив стоимость.
Мне в этом случае `addadItem` еще раз в массив в стейте не нужно добавлять, а нужно заменить старый на новый.

2018-07-30 12:33 UTC, foxy-eyed commented on src/components/ProductAddButton.js
> +function ProductAddButton({ product }) {
А есть какие-то конвенции, связанные с именованием компонентов?
Глагол на первом месте `AddToCartButton` – это норм?
Я, честно говоря, такое название дала, потому что файлы в каталоге с компонентами тогда красиво сортируются (все, относящееся к продукту, рядышком :))

2018-07-30 12:55 UTC, merged

2018-07-30 13:07 UTC, index01d commented on src/components/ProductAddButton.js
> +function ProductAddButton({ product }) {
конвенций определенных нет, замечание продиктовано тем что не ясно куда его девают продукт то этот, а так сразу ясно что это кусок корзины :) насчет глагола: почему нет?:)

2018-07-30 13:08 UTC, index01d commented on src/components/ProductAddButton.js
> +function ProductAddButton({ product }) {
есть впрочем серия книжек аля Clean Code, Refactoring и библия Совершенный код Макконелла  (Code Complete), которые наставляют "на путь истинный".

2018-07-30 13:10 UTC, index01d commented on src/components/ProductAddButton.js
> +function ProductAddButton({ product }) {
в последней переменным очень много посвящено:) так что советую как минимум пролистать по диагонали