Lesson4
foxy-eyed/helloReact pull request #5
Opened 2018-08-02 18:52 UTC by foxy-eyed

- [x] Установите react-router и react-router-dom
- [x] Сконфигурируйте роуты главной страницы (страница каталога товаров), внутренней страницы о товаре, корзины, страницу контактов (саму страничку тоже создайте); Роуты необходимо сконфигурировать как plain routes (Non-JSX)
- [x] Реализуйте главное меню
- [x] Реализуйте переход в корзину по нажатию на кнопку корзины, реализованную в предыдущем занятии.
- [x] Реализуйте страницу с ошибкой 404 (не найдено)

![rixemhiknk](https://user-images.githubusercontent.com/19491749/43604294-76928fcc-96a6-11e8-9ef3-5c53157404d0.gif)

2018-08-05 10:00 UTC, index01d requested changes
Предлагаю поработать со структурой директорий:
выделим в components директорию elements с общими компонентами Link/NavLink, Image итп; директорию views где каждый компонент это страница:
```
views/
- Catalog/
-- Card.js
-- Catalog.js
-- index.js
- Cart/
-- ...
- - index.js
```
и если нужно, то можно выделить директорию shared с общими виджетами

2018-08-06 09:51 UTC, index01d requested changes
Получилось четко! но стоит в shared в директорию сложить `ProductCard` и `ProductAddButton` (AddToCartButton, к слову), тк второе является частью первого, заодно можно будет избавиться от префикса Product в начале названия файла

2018-08-06 13:00 UTC, index01d approved these changes

2018-08-06 13:00 UTC, index01d commented
мержить будет как-то сложно:)

2018-08-06 13:17 UTC, foxy-eyed commented
@index01d не страшно, вроде)

2018-08-06 13:17 UTC, merged